DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts CASCADE;

CREATE TABLE IF NOT EXISTS users (
    "user_id" SERIAL NOT NULL PRIMARY KEY,
    "username" VARCHAR(32) NOT NULL,
    "password" VARCHAR(32) NOT NULL,
    "name_color" VARCHAR(32) NULL
);

CREATE TABLE IF NOT EXISTS posts (
    "post_id" SERIAL NOT NULL PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES users(user_id),
    "text" VARCHAR(200) NOT NULL
);